services:
  selenium-hub6:
    image: selenium/hub:latest
    container_name: selenium-hub6
    ports:
      - "4461:4461"
      - "4462:4462"
      - "4463:4463"
      - "4466:4466"

  chrome6:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub6
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub6
      - SE_EVENT_BUS_PUBLISH_PORT=4462
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4463
      