services:
  selenium_hub6:
    image: selenium/hub:latest
    container_name: selenium_hub6
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
  
  chrome:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium_hub6
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub6
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  
  chrome1:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium_hub6
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub6
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443    
  
  nexus_7.1.1:
    image: oklabs/docker-android-x86-7.1.1:latest
    privileged: true
    scale: 1
    depends_on:
      - selenium_hub6
    ports:
      - 6080:6080
      - 4723:4723
      - 5554:5554
      - 5555:5555
    volumes:
      - $PWD/example/sample_apk:/root/tmp/sample_apk
      - ./video-nexus_7.1.1:/tmp/video
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub6
      - AUTO_RECORD=true
